package myapp;


import database.Database;
import java.awt.BasicStroke;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import database.Database;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class registrationForm extends javax.swing.JFrame {
    
   

    /**
     * Creates new form login
     */
    public registrationForm() {
        initComponents();
       Connection con = Database.connectDB();
    }
    
    Color hover = new Color(024,204,204);
    Color defbutton = new Color (140,104,141);
    
    Border empty = BorderFactory.createEmptyBorder();
    
    void buttonBorderAnimation(JPanel panel){
     panel.setBackground(hover);
     panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
     panel.setBorder(BorderFactory.createStrokeBorder(new BasicStroke(2.0f)));
    }
    
    
    void buttonDefaultColor(JPanel panel){
        panel.setBackground(defbutton);
        panel.setBorder(empty);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        register = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        cancel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        username_field1 = new javax.swing.JTextField();
        username_field2 = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        username_field3 = new javax.swing.JTextField();
        number = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        username_field4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Untitled design.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 730, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 440, 510));

        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 160, 30));

        username.setBackground(new java.awt.Color(0, 0, 0));
        username.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        username.setText("Username:");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 80, 30));

        password.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        password.setText("Password:");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 70, 30));

        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 160, 30));

        register.setBackground(new java.awt.Color(187, 187, 187));
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });

        label.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label.setText("REGISTER");
        register.add(label);

        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 70, 30));

        cancel.setBackground(new java.awt.Color(187, 187, 187));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("CANCEL");
        cancel.add(jLabel6);

        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 70, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REGISTRATION FORM");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        minimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("—");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 40, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Already have an account? Click here to Login");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, -1, -1));

        fullname.setBackground(new java.awt.Color(0, 0, 0));
        fullname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        fullname.setText("Full name:");
        getContentPane().add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 80, 30));

        username_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_field1ActionPerformed(evt);
            }
        });
        getContentPane().add(username_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 160, 30));

        username_field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_field2ActionPerformed(evt);
            }
        });
        getContentPane().add(username_field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 160, 30));

        email.setBackground(new java.awt.Color(0, 0, 0));
        email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        email.setText("Email:");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 80, 30));

        username_field3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_field3ActionPerformed(evt);
            }
        });
        getContentPane().add(username_field3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 160, 30));

        number.setBackground(new java.awt.Color(0, 0, 0));
        number.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        number.setText("Number:");
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 80, 30));

        type.setBackground(new java.awt.Color(0, 0, 0));
        type.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        type.setText("Type:");
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 80, 30));

        username_field4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_field4ActionPerformed(evt);
            }
        });
        getContentPane().add(username_field4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 160, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_fieldActionPerformed

    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_fieldActionPerformed

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        buttonBorderAnimation(cancel);
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        buttonDefaultColor(cancel);
    }//GEN-LAST:event_cancelMouseExited

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        buttonBorderAnimation(register);
    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited
        buttonDefaultColor(register);
    }//GEN-LAST:event_registerMouseExited

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        dashboard dash = new  dashboard();
        this.dispose();
        dash.setVisible(true);
        
            if((!email.getText().isEmpty() || !username.getText().isEmpty())|| !fullname.getText().isEmpty() && !password.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "All Fields are required","Error", JOptionPane.ERROR_MESSAGE);
        } else {
                Database db = new Database();
                String sql = "INSERT INTO users (fullname,username,email,password,type,status)VALUES (?,?,?,?,?,?)";
                db.addRecord(sql, fullname.getText(), username.getText(),email.getText(), "Inactive", type.getText(),password.getText());
        }
    }//GEN-LAST:event_registerMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void username_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_field1ActionPerformed

    private void username_field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_field2ActionPerformed

    private void username_field3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_field3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_field3ActionPerformed

    private void username_field4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_field4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_field4ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        login lf = new  login();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancel;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel number;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JPanel register;
    private javax.swing.JLabel type;
    private javax.swing.JLabel username;
    private javax.swing.JTextField username_field;
    private javax.swing.JTextField username_field1;
    private javax.swing.JTextField username_field2;
    private javax.swing.JTextField username_field3;
    private javax.swing.JTextField username_field4;
    // End of variables declaration//GEN-END:variables
}
